### ISSUE TITLE
needs to be updated to current python and qt 

### ISSUE THREAD

**Issue by JohnVV** [josauder/procedural_city_generation#27]
this is my qt4 python2.7 error 
--- quote ---
You have selected a heightmap which has no .txt file yet, OR the given .txt file has the wrong dimensions. The parameter heightDif will be used to describe the height difference between the lowest and the highest points on the map.
Processing image
('Processed image being saved as ', u'stubs_height.png')
Traceback (most recent call last):
  File "GUI.py", line 207, in start_roadmap
    UI.roadmap()
  File "/xxx/xxx/xxx/xxx/xxx/procedural_city_generation-master/UI.py", line 58, in roadmap
    roadmap_main.main()
  File "/xxx/xxx/xxx/xxx/xxx/procedural_city_generation-master/procedural_city_generation/roadmap/main.py", line 39, in main
    front=iteration(front)
  File "/xxx/xxx/xxx/xxx/xxx/procedural_city_generation-master/procedural_city_generation/roadmap/iteration.py", line 26, in iteration
    for suggested_vertex in getSuggestion(vertex):
  File "/xxx/xxx/xxx/xxx/xxx/procedural_city_generation-master/procedural_city_generation/roadmap/getSuggestion.py", line 25, in getSuggestion
    rule= getRule(vertex)
  File "/xxx/xxx/xxx/xxx/xxx/procedural_city_generation-master/procedural_city_generation/roadmap/getRule.py", line 27, in getRule
    population_density = np.sqrt((singleton.img2[singleton.img2.shape[0]-y*singleton.img2.shape[0]][x*singleton.img2.shape[1]][0])/255)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

----- end quote ----

this tool DID work last year or two back on opensuse 42.2 and 42.3 

But not running on OpenSUSE tumbleweed linux 
Python 2.7.15 and Python 3.6.5

**Comment by galalen** [comment]
Currently, I'm working make it works on python 3.6+ and pyqt5. I just finished code UI issues
